//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loteria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookAppEntities : DbContext
    {
        public BookAppEntities()
            : base("name=BookAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Nagrodas> Nagrodas { get; set; }
        public virtual DbSet<Odpowiedzs> Odpowiedzs { get; set; }
        public virtual DbSet<Pytanies> Pytanies { get; set; }
        public virtual DbSet<Uczestniks> Uczestniks { get; set; }
    }
}
