//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nagrodas
    {
        public int nagrodaId { get; set; }
        public string nagroda { get; set; }
        public Nullable<int> Uczestnik_uczestnikId { get; set; }
    
        public virtual Uczestniks Uczestniks { get; set; }
    }
}
