//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odpowiedzs
    {
        public int odpowiedzId { get; set; }
        public string tresc { get; set; }
        public bool poprawnoscOdpowiedzi { get; set; }
        public int pytanieId { get; set; }
    
        public virtual Pytanies Pytanies { get; set; }
    }
}
